#version: '3.8'
#services:
#  app:
#    build: .
#    container_name: pilotes-order-system
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_PROFILES_ACTIVE: docker
#    volumes:
#      - .:/app
#    command: ["./mvnw", "spring-boot:run"]
#
#  kafka:
#    image: wurstmeister/kafka:2.13-2.6.0
#    ports:
#      - "9092:9092"
#    environment:
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#
#  zookeeper:
#    image: wurstmeister/zookeeper:3.4.6
#    ports:
#      - "2181:2181"
